spring.application.name=flow-forge-engine

server.port=8080
server.servlet.context-path=/

spring.datasource.url=jdbc:postgresql://localhost:5432/flowForge
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

logging.level.root=INFO
logging.level.com.flowforge=DEBUG
